#服务器配置
server:
  servlet:
    # 编码配置
    encoding:
      charset: UTF-8
      force: true
  port: 80
#spring配置
spring:
  application:
    name: hospital-doctor
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 1024MB
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置日志地址
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      codingapi:
        txlcn: DEBUG
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

# mybatis
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xlh.modules.**.bean
  #typeEnumsPackage: org.springblade.dashboard.bean.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: assign_id
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ServerListRefreshInterval: 2000
  ReadTimeout: 60000
  ConnectTimeout: 60000