#server:
#  port: 7001
#eureka:
#  instance:
#    hostname: localhost #eureka服务端的实例名称
#  client:
#    register-with-eureka: false #不像注册中心注册自己
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
#  server:
#    #关闭自我保护机制，保证不可用服务被及时剔除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    hostname: eureka
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  server:
    eviction-interval-timer-in-ms: 5000
    use-read-only-response-cache: false